# Generated by Django 5.2.8 on 2025-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('importance', models.IntegerField()),
                ('estimated_hours', models.FloatField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('score', models.FloatField()),
                ('priority', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
